version: '3.4'

services:
  app:
    environment:
      ENV: localdev
      PORT: 8000
      AUTH: BLTI_DEV
      LTI_DEVELOP_APP: libguide
    restart: always
    container_name: app-libguide
    build:
      context: .
      target: app-container
    volumes:
      - ./libguide:/app/libguide
    ports:
      - "8000:8000"
