autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
targetAverageUtilization: 100
affinity:
   podsSpanNodes: true

ingress:
  enabled: true
  tls:
    libguides:
      secretName: libguides.canvas.uw.edu-ingress-cert
      hosts:
        - libguides.canvas.uw.edu
  hosts:
    libguides:
      host: libguides.canvas.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

lifecycle:
  enabled: true
  preStop:
    enabled: true
readiness:
  enabled: true

database:
  engine: null

repo: libguides
instance: prod
namespace:
  enabled: true

memcached:
  enabled: true
  replicaCount: 2
  updateStrategy:
    type: RollingUpdate

certs:
  mounted: true
  certPath: /certs/libguides.canvas.uw.edu-ic.cert
  keyPath: /certs/libguides.canvas.uw.edu-ic.key
  secretName: libguides.canvas.uw.edu-ic-certs

environmentVariables:
  - name: CLUSTER_CNAME
    value: libguides.canvas.uw.edu
  - name: AUTH
    value: BLTI
  - name: ENV
    value: prod
  - name: SESSION_BACKEND
    value: MEMCACHED
  - name: LIBCURRICS_ENV
    value: PROD
  - name: LIBCURRICS_TIMEOUT
    value: "5"
  - name: LTI_CONFIG_DIRECTORY
    value: /lti/config

externalSecrets:
  enabled: true
  secrets:
    - name: libguides.canvas.uw.edu-secrets
      externalKey: libguides/prod/secrets
      data:
        - name: django-secret
          property: django-secret
    - name: libguides.canvas.uw.edu-canvas-secrets
      externalKey: libguides/shared/secrets
      data:
        - name: lti-consumers
          property: lti-consumers
        - name: blti-aes-key
          property: blti-aes-key
        - name: blti-aes-iv
          property: blti-aes-iv
    - name: libguides.canvas.uw.edu-lti-keys
      externalKey: libguides/prod/lti-keys
      data:
        - name: private-key-1.key
          property: private-key-1.key
        - name: public-key-1.key
          property: public-key-1.key
    - name: libguides.canvas.uw.edu-ic-certs
      externalKey: libguides/prod/ic-certs
      data:
        - name: libguides.canvas.uw.edu-ic.cert
          property: libguides.canvas.uw.edu-ic.cert
        - name: libguides.canvas.uw.edu-ic.key
          property: libguides.canvas.uw.edu-ic.key

environmentVariablesSecrets:
  django-secret:
    name: DJANGO_SECRET
    secretName: libguides.canvas.uw.edu-secrets
    secretKey: django-secret
  LTIConsumers:
    name: LTI_CONSUMERS
    secretName: libguides.canvas.uw.edu-canvas-secrets
    secretKey: lti-consumers
  BLTIAESKey:
    name: BLTI_AES_KEY
    secretName: libguides.canvas.uw.edu-canvas-secrets
    secretKey: blti-aes-key
  BLTIAESIV:
    name: BLTI_AES_IV
    secretName: libguides.canvas.uw.edu-canvas-secrets
    secretKey: blti-aes-iv

mountedSecrets:
  enabled: true
  mountPath: /lti/keys
  secretName: libguides.canvas.uw.edu-lti-keys

podVolumes:
  lti-tool-config:
    volume:
      configMap:
        name: lti-tool-config
    mount:
      mountPath: /lti/config
    containers: [base]

configmaps:
  lti-tool-config:
    tool.json: |
      {
        "https://canvas.instructure.com": [{
          "default": true,
          "client_id": "100000000000805",
          "auth_login_url": "https://sso.canvaslms.com/api/lti/authorize_redirect",
          "auth_token_url": "https://sso.canvaslms.com/login/oauth2/token",
          "key_set_url": "https://sso.canvaslms.com/api/lti/security/jwks",
          "private_key_file": "/lti/keys/private-key-1.key",
          "public_key_file": "/lti/keys/public-key-1.key",
          "deployment_ids": ["212930:c78d46b24c785a8ad37b5bf9bdf26ceb32cc9d18"]
        }]
      }
