ingress:
  enabled: true
  tls:
    libguides:
      secretName: test-libguides.canvas.uw.edu-ingress-cert
      hosts:
        - test-libguides.canvas.uw.edu
  hosts:
    libguides:
      host: test-libguides.canvas.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
database:
  engine: null
repo: libguides
instance: test
image:
  repository: registry.hub.docker.com/acait/libguides
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
certs:
  mounted: true
  certPath: /certs/test-libguides.canvas.uw.edu-uwca.cert
  keyPath: /certs/test-libguides.canvas.uw.edu-uwca.key
  secretName: test-libguides.canvas.uw.edu-uwca-certs
environmentVariables:
  - name: CLUSTER_CNAME
    value: test-libguides.canvas.uw.edu
  - name: AUTH
    value: BLTI
  - name: ENV
    value: test
  - name: SESSION_BACKEND
    value: MEMCACHED
  - name: LIBCURRICS_ENV
    value: PROD
  - name: LIBCURRICS_TIMEOUT
    value: "5"
externalSecrets:
  enabled: true
  secrets:
    - name: test-libguides.canvas.uw.edu-secrets
      externalKey: axdd/kv/data/libguides/test/secrets
      data:
        - name: django-secret
          property: django-secret
    - name: test-libguides.canvas.uw.edu-canvas-secrets
      externalKey: axdd/kv/data/libguides/shared/secrets
      data:
        - name: lti-consumers
          property: lti-consumers
        - name: blti-aes-key
          property: blti-aes-key
        - name: blti-aes-iv
          property: blti-aes-iv
    - name: test-libguides.canvas.uw.edu-uwca-certs
      externalKey: axdd/kv/data/libguides/test/uwca-certs
      data:
        - name: test-libguides.canvas.uw.edu-uwca.cert
          property: test-libguides.canvas.uw.edu-uwca.cert
        - name: test-libguides.canvas.uw.edu-uwca.key
          property: test-libguides.canvas.uw.edu-uwca.key
environmentVariablesSecrets:
  django-secret:
    name: DJANGO_SECRET
    secretName: test-libguides.canvas.uw.edu-secrets
    secretKey: django-secret
  LTIConsumers:
    name: LTI_CONSUMERS
    secretName: test-libguides.canvas.uw.edu-canvas-secrets
    secretKey: lti-consumers
  BLTIAESKey:
    name: BLTI_AES_KEY
    secretName: test-libguides.canvas.uw.edu-canvas-secrets
    secretKey: blti-aes-key
  BLTIAESIV:
    name: BLTI_AES_IV
    secretName: test-libguides.canvas.uw.edu-canvas-secrets
    secretKey: blti-aes-iv
