ingress:
  enabled: true
  tls:
    libguides:
      secretName: test-libguides.canvas.uw.edu-ingress-cert
      hosts:
        - test-libguides.canvas.uw.edu
  hosts:
    libguides:
      host: test-libguides.canvas.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
securityPolicy:
  enabled: true
database:
  engine: null
repo: libguides
instance: test
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
certs:
  mounted: true
  certPath: /certs/test-libguides.canvas.uw.edu-ic.cert
  keyPath: /certs/test-libguides.canvas.uw.edu-ic.key
  secretName: test-libguides.canvas.uw.edu-ic-certs
environmentVariables:
  - name: CLUSTER_CNAME
    value: test-libguides.canvas.uw.edu
  - name: AUTH
    value: BLTI
  - name: ENV
    value: test
  - name: SESSION_BACKEND
    value: MEMCACHED
  - name: LIBCURRICS_ENV
    value: PROD
  - name: LIBCURRICS_TIMEOUT
    value: "5"
  - name: LTI_CONFIG_DIRECTORY
    value: /lti/config
externalSecrets:
  enabled: true
  secrets:
    - name: test-libguides.canvas.uw.edu-secrets
      externalKey: libguides/test/secrets
      data:
        - name: django-secret
          property: django-secret
    - name: test-libguides.canvas.uw.edu-lti-keys
      externalKey: libguides/test/lti-keys
      data:
        - name: private-key-1.key
          property: private-key-1.key
        - name: public-key-1.key
          property: public-key-1.key
    - name: test-libguides.canvas.uw.edu-canvas-secrets
      externalKey: libguides/shared/secrets
      data:
        - name: lti-consumers
          property: lti-consumers
        - name: blti-aes-key
          property: blti-aes-key
        - name: blti-aes-iv
          property: blti-aes-iv
    - name: test-libguides.canvas.uw.edu-ic-certs
      externalKey: libguides/test/ic-certs
      data:
        - name: test-libguides.canvas.uw.edu-ic.cert
          property: test-libguides.canvas.uw.edu-ic.cert
        - name: test-libguides.canvas.uw.edu-ic.key
          property: test-libguides.canvas.uw.edu-ic.key
environmentVariablesSecrets:
  django-secret:
    name: DJANGO_SECRET
    secretName: test-libguides.canvas.uw.edu-secrets
    secretKey: django-secret
  LTIConsumers:
    name: LTI_CONSUMERS
    secretName: test-libguides.canvas.uw.edu-canvas-secrets
    secretKey: lti-consumers
  BLTIAESKey:
    name: BLTI_AES_KEY
    secretName: test-libguides.canvas.uw.edu-canvas-secrets
    secretKey: blti-aes-key
  BLTIAESIV:
    name: BLTI_AES_IV
    secretName: test-libguides.canvas.uw.edu-canvas-secrets
    secretKey: blti-aes-iv

mountedSecrets:
  enabled: true
  mountPath: /lti/keys
  secretName: test-libguides.canvas.uw.edu-lti-keys

podVolumes:
  lti-tool-config:
    volume:
      configMap:
        name: lti-tool-config
    mount:
      mountPath: /lti/config
    containers: [base]

configmaps:
  lti-tool-config:
    tool.json: |
      {
        "https://canvas.test.instructure.com": [{
          "default": true,
          "client_id": "100000000000805",
          "auth_login_url": "https://sso.test.canvaslms.com/api/lti/authorize_redirect",
          "auth_token_url": "https://sso.test.canvaslms.com/login/oauth2/token",
          "key_set": null,
          "key_set_url": "https://sso.test.canvaslms.com/api/lti/security/jwks",
          "private_key_file": "/lti/keys/private-key-1.key",
          "public_key_file": "/lti/keys/public-key-1.key",
          "deployment_ids": ["208223:c61ffdb94ad935f3abe694d5f29862298b991894"]
        }]
      }
